version: '3'
services:
  app:
    container_name: FullStackJS
    restart: always
    build: ./
    ports:
      - '9000:3000'
    links:
      - mongo
    environment:
      DB_SERVER: mongo
      DB_PORT: 27017
      PORT: 3000

  mongo:
    container_name: mongo
    image: mongo:4.0.11
    ports:
      - '27017:27017'
  